name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macOS-10.14, windows-2019]
        version: ['1.26.0', '', 'insiders']

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
         
      - name: Install Dependencies
        run: 'npm ci || npm ci'
        shell: bash
      
      - name: Lint files
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run style-check

      - name: Compile sources
        run: npm run build
      
      - name: Enable full coverage
        run: sed -i.bak 's/"\*"//g' package.json
        shell: bash
      
      - name: Start xvfb
        if: startsWith(matrix.os, 'ubuntu')
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run tests
        env:
          CODE_VERSION: ${{ matrix.version }}
          DISPLAY: ':99.0'
        run: npm run test
      
      - name: Publish Code Coverage to Codecov
        if: startsWith(matrix.os, 'ubuntu') && matrix.version == ''
        run: node_modules/.bin/codecov --disable=gcov
        env:
          CODECOV_TOKEN: ${{ secrets.codecovToken }}
      
      - name: Release
        if: startsWith(matrix.os, 'ubuntu') && matrix.version == '' && github.ref == 'refs/heads/master' && github.repository == 'JohnstonCode/svn-scm'
        run: npm run semantic-release
        env:
          VSCE_TOKEN: ${{ secrets. vsceToken }}
          GH_TOKEN: ${{ secrets.githubToken }}
          GIT_AUTHOR_EMAIL: ${{ secrets.gitEmail }}
          GIT_COMMITTER_EMAIL: ${{ secrets.gitEmail }}
          GIT_AUTHOR_NAME: ${{ secrets.gitName }}
          GIT_COMMITTER_NAME: ${{ secrets.gitName }}
